version: '3'

services:
  web:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./code:/var/www/html:ro
    ports:
      - "8080:80"
  php:
    build: .
    volumes:
      - ./code:/var/www/html
